all:
	happy -gca Tip/Parser/ParTIP.y
	alex -g Tip/Parser/LexTIP.x
	ghc --make Tip/Parser/TestTIP.hs -o Tip/Parser/TestTIP

clean:
	-rm -f Tip/Parser/*.log Tip/Parser/*.aux Tip/Parser/*.hi Tip/Parser/*.o Tip/Parser/*.dvi

distclean: clean
	-rm -f Tip/Parser/DocTIP.* Tip/Parser/LexTIP.* Tip/Parser/ParTIP.* Tip/Parser/LayoutTIP.* Tip/Parser/SkelTIP.* Tip/Parser/PrintTIP.* Tip/Parser/TestTIP.* Tip/Parser/AbsTIP.* Tip/Parser/TestTIP Tip/Parser/ErrM.* Tip/Parser/SharedString.* Tip/Parser/ComposOp.* Tip/Parser/TIP.dtd Tip/Parser/XMLTIP.* Makefile*
		-rmdir -p Tip/Parser/

